s="Hello World"
print(s.lower())
print(s.upper())
print('s' in s)
print('s' not in s)
print(s[0:4])
print(s[0:10:2])
print(s[0:])
print(s.count('l'))
print(s.capitalize())
print(s.casefold())
print(s.center(2))
print(s.encode())
print(s.endswith('o'))
print(s.expandtabs())
print(s.find('H'))
print(s.format())
print(s.index('e'))
print(s.isalnum())
print(s.isalpha())
print(s.isascii())
print(s.isdecimal())
print(s.isidentifier())
print(s.lower())
print(s.istitle())
print(s.lstrip())
print(s.isdigit())
print(s.partition('e'))
print(s.replace('o','t'))
print(s.rfind('l'))
print(s.isspace())
print(s.isprintable())
print(s.join('H'))
print(s.title())